use tcconfig (python) to make life easier on setting thru put limits

diff --git a/create_ap_test b/create_ap_test
--- a/create_ap_test
+++ b/create_ap_test
@@ -21,8 +21,10 @@ DELAY_DEST_PORT=1883
 #####################################
 
 ######  iptable filter en/dis  ######
-# DROP_OUTBOUND_EN=yes
-DROP_OUTBOUND_EN=no
+DROP_OUTBOUND_EN=yes
+# DROP_OUTBOUND_EN=no
+
+RM_WIFI_IF=""
 
 DELAY_EN=yes
 # DELAY_EN=no
@@ -49,70 +51,59 @@ format_drop_iptable_rule () {
 #####################################
 
 #########    Delay filter   #########
-DELAY_TYPE=1
-# DELAY_TYPE=2
-# DELAY_TYPE=3
+SIMPLE_DELAY=1
+NORMAL_DIST_DELAY=2
+VARIANCE_DELAY=3
 
-TC_USER=root
-
-# Delay base for all types (for type 1 its the only setting)
+# Delay base for all types
 DELAY_TIME_MS=100
 # Delay variance for type 2
 DELAY_VAR_PCT=25
 # Delay normal dist for type 3
 DELAY_DISTRIBUTION=20
 
-format_delay_rule () {
-   local cmd="";
-   local outputtmp="";
-   if [[ "$DELAY_EN" == "yes" ]]; then
-      local IFACE=$1;
-      local PARAM=$2;
-      local TYPE=$3;
-      local cmdswitch="";
-      case $TYPE in
-         "1") echo "basic delay" >&2; cmdswitch="$DELAY_TIME_MS"; cmdswitch+="ms";
-         ;;
-         "2") echo "variance delay" >&2; cmdswitch="$DELAY_TIME_MS"; cmdswitch+="ms";
-         ;;
-         "3") echo "normal dist delay" >&2; cmdswitch="$DELAY_TIME_MS"; cmdswitch+="ms";
-         ;;
-         *) echo "Invalid or wrong arg!">&2; echo "Call with '1' for debug or '2' for release." >&2;
-         echo '';
-         ;;
-      esac
-      cmd=(tc qdisc "$PARAM" dev "$IFACE" "$TC_USER" netem delay $cmdswitch);
-   fi
-   outputtmp="${cmd[@]}";
-   echo $outputtmp
+set_delay_rules() {
+   local IFACE=$1;
+   local TYPE=$2;
+   local PARAM_DBG='';
+   local ADD_DELAY_CMD='';
+   case "$TYPE" in
+      "1") echo "basic delay" >&2;
+         local DELAY1=$3;
+         PARAM_DBG+="Delay=$DELAY1";
+         ADD_DELAY_CMD=(tcset --device $IFACE --delay $DELAY1)
+      ;;
+      "2") echo "normal dist delay" >&2;
+         local DELAY1=$3;
+         local DELAY_DIST=$4;
+         PARAM_DBG+="Delay=$DELAY1";
+         PARAM_DBG+="Delay dist=$DELAY_DIST";
+         ADD_DELAY_CMD=(tcset --device $IFACE --delay $DELAY1 $DELAY_DIST)
+      ;;
+      "3") echo "variance delay" >&2;
+         local DELAY1=$3;
+         local DELAY_DIST=$4;
+         local DELAY_PCT=$5;
+         PARAM_DBG+="Delay=$DELAY1";
+         PARAM_DBG+="Delay dist=$DELAY_DIST";
+         PARAM_DBG+="Delay pct=$DELAY_PCT %";
+         ADD_DELAY_CMD=(tcset --device $IFACE --delay $DELAY1 $DELAY_DIST $DELAY_PCT)
+      ;;
+      *) echo "Invalid or wrong arg!">&2;
+         return;
+      ;;
+   esac
+   printf "Adding rule: $TYPE to if $IFACE and params:\n$PARAM_DBG";
+   printf "\n${ADD_DELAY_CMD[@]}\n" >&2;
+   ${ADD_DELAY_CMD[@]};
 }
 
 clear_delay_rules() {
    local IFACE=$1;
-   local TYPE=$2;
-   local DEL_DELAY_CMD='';
-   LIST_DELAY_CMD=$(eval 'tc -p qdisc ls dev $IFACE')
-   if [[ "$LIST_DELAY_CMD" != "" ]]; then
-      DEL_DELAY_CMD=$(format_delay_rule "$IFACE" "$DELARG" "$TYPE")
-      echo "$LIST_DELAY_CMD - exists!";
-      echo 'Deleting...';
-      ${DEL_DELAY_CMD[@]};
-   else
-      echo 'DNE';
-   fi
-}
-
-add_delay_rule() {
-   local IFACE=$1;
-   local TYPE=$2;
-   LIST_DELAY_CMD=$(eval 'tc -p qdisc ls dev $IFACE')
-   if [[ "$LIST_DELAY_CMD" == "" ]]; then
-      ADD_DELAY_CMD=$(format_delay_rule "$IFACE" "$ADDARG" "$TYPE")
-      ${ADD_DELAY_CMD[@]};
-      printf "${DEL_DELAY_CMD[@]}\n";
-   else
-      printf "Delay already set!\n";
-   fi
+   echo 'clear_delay_rules...';
+   DEL_DELAY_CMD=(tcdel --device $IFACE)
+   printf "\n${DEL_DELAY_CMD[@]}\n" >&2;
+   ${DEL_DELAY_CMD[@]};
 }
 
 # clear_delay_rules "$WIFI_IFACE" "$DELAY_TYPE";
@@ -773,7 +764,7 @@ _clean_custom_iptables() {
    echo "${RM_DROP_OUTBOUND_CMD[@]}" >&2;
    ${RM_DROP_OUTBOUND_CMD[@]};
 
-   clear_delay_rules "$WIFI_IFACE" "$DELAY_TYPE";
+   clear_delay_rules "$WIFI_IFACE";
 }
 
 _cleanup() {
@@ -1676,8 +1667,7 @@ if [[ $NO_VIRT -eq 0 ]]; then
         # now we can call networkmanager_wait_until_unmanaged
         networkmanager_is_running && [[ $NM_OLDER_VERSION -eq 0 ]] && networkmanager_wait_until_unmanaged ${VWIFI_IFACE}
         echo "${VWIFI_IFACE} created." >&2;
-        ${VWIFI_IFACE}
-        echo "Setting ${VWIFI_IFACE} delay to ";
+        RM_WIFI_IF=$VWIFI_IFACE
     else
         VWIFI_IFACE=
         die "$VIRTDIEMSG"
@@ -1846,14 +1836,16 @@ if [[ "$SHARE_METHOD" != "none" ]]; then
         iptables -w -t nat -I POSTROUTING -s ${GATEWAY%.*}.0/24 ! -o ${WIFI_IFACE} -j MASQUERADE || die
         iptables -w -I FORWARD -i ${WIFI_IFACE} -s ${GATEWAY%.*}.0/24 -j ACCEPT || die
         # insert drop
-        INS_DROP_OUTBOUND_CMD=$(format_drop_iptable_rule "$WIFI_IFACE" "$DASH_INSERT")
-        echo "${INS_DROP_OUTBOUND_CMD[@]}" >&2;
-        ${INS_DROP_OUTBOUND_CMD} || die;
+        if [[ "$DROP_OUTBOUND_EN" == "yes" ]]; then
+           INS_DROP_OUTBOUND_CMD=$(format_drop_iptable_rule "$WIFI_IFACE" "$DASH_INSERT")
+           printf "\n${INS_DROP_OUTBOUND_CMD[@]}\n" >&2;
+           ${INS_DROP_OUTBOUND_CMD} || die;
+        fi
         # Set delays
-        add_delay_rule "$WIFI_IFACE" "$DELAY_TYPE";
-        # if [[ "$DROP_OUTBOUND_EN" == "yes" ]]; then
-        #   iptables -w -I FORWARD -i ${WIFI_IFACE} -d $DROP_DEST_IPMASK -p tcp --dport $DROP_DEST_PORT -m statistic --mode random --probability $DROP_OUTBOUND_PCT -j DROP || die
-        # fi
+        clear_delay_rules "$WIFI_IFACE"
+        if [[ "$DELAY_EN" == "yes" ]]; then
+            set_delay_rules "$WIFI_IFACE" "$SIMPLE_DELAY" "100";
+        fi
         iptables -w -I FORWARD -i ${INTERNET_IFACE} -d ${GATEWAY%.*}.0/24 -j ACCEPT || die
         echo 1 > /proc/sys/net/ipv4/conf/$INTERNET_IFACE/forwarding || die
         echo 1 > /proc/sys/net/ipv4/ip_forward || die
